# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Pre Flight Checks
      run: |
        mkdir /home/runner/work/_temp/my_dir
        chmod 777 /home/runner/work/_temp/my_dir
        mkdir /home/runner/work/_temp/unzipped
        chmod 777 /home/runner/work/_temp/unzipped
        # https://github.com/dwyl/aws-lambda-deploy/pull/92#issuecomment-1910566973
        mkdir /home/runner/work/_temp/fakedir
        chmod 777 /home/runner/work/_temp/fakedir
        mkdir /home/runner/work/_temp/dist
        chmod 777 /home/runner/work/_temp/dist
        echo "export HELLO=world" >> /home/runner/work/aws-lambda-deploy/aws-lambda-deploy/.env 
        cat /home/runner/work/aws-lambda-deploy/aws-lambda-deploy/.env

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm run lint
    - run: npm test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
        AWS_REGION: "eu-west-1"
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
        TMPDIR: ${{ runner.temp }}/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
